#!/bin/sh
vimdiff ~/.inputrc ./bash/.inputrc
vimdiff ~/.bashrc ./bash/.bashrc
vimdiff ~/.dir_colors ./bash/.dir_colors
vimdiff ~/.vimrc ./vim/.vimrc
vimdiff ~/.config/kitty/kitty.conf ./kitty/kitty.conf
