#!/bin/bash
# Script to pre-configure & install needed packages
set -e

# Run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root."
    exit
fi

################################################################################
echo "*** Installing system utilities"
dnf install -y --allowerasing \
	mc vim vim-X11 vim-default-editor ctags kitty xterm fish sshfs colordiff meld \
	imwheel \
	bsd-games cmatrix \
	smartmontools htop dnfdragora gnome-tweak-tool dconf-editor \
	curl cabextract \
	xterm xorg-x11-fonts* xorg-x11-font-utils fontconfig \
	gnome-shell-extension-common.noarch \
	gnome-shell-extension-apps-menu gnome-shell-extension-background-logo \
	gnome-shell-extension-dash-to-dock gnome-shell-extension-drive-menu \
	gnome-shell-extension-horizontal-workspaces gnome-shell-extension-launch-new-instance \
	gnome-shell-extension-places-menu gnome-shell-extension-pomodoro \
	gnome-shell-extension-system-monitor-applet gnome-shell-extension-topicons-plus \
	gnome-shell-extension-user-theme gnome-shell-extension-window-list \
	gnome-shell-extension-windowoverlay-icons gnome-shell-extension-workspace-indicator \
	la-capitaine-cursor-theme la-capitaine-icon-theme \
	qalculate-gtk \

################################################################################
echo "*** Installing development libraries"
dnf install -y \
	git git-extras git-filter-repo \
	gcc gcc-c++ make binutils automake pkg-config \
	protobuf-compiler \
	gobject-introspection-devel cairo-devel gtk3 cairo-gobject-devel \
	java-1.8.0-openjdk \

################################################################################
echo "*** Installing tools..."
dnf install -y \
	python3 python3-pip python3-devel python3-wheel python3-setuptools python3-six \
	python3-spyder python3-notebook python-notebook-doc \
	python3-ipdb python3-coverage python3-coverage_pth python3-mock \
	python3-pytz python3-tzlocal \
	python3-numpy python3-pandas python3-scipy python3-scikit-learn python3-statsmodels \
	python3-matplotlib python3-seaborn \
	python3-defusedxml \
	python3-aiohttp \
	python3-retrying \
	python3-urwid \

################################################################################
echo "*** Installing ZeroMQ..."
dnf install -y zeromq czmq python3-zmq

################################################################################
echo "*** Installing PostrgreSQL..."
rpm -ihv https://ftp.postgresql.org/pub/pgadmin/pgadmin4/yum/pgadmin4-fedora-repo-1-1.noarch.rpm
dnf install -y postgresql postgresql-server postgresql-contrib postgresql-upgrade \
	postgresql-jdbc postgresql-plpython3 python3-psycopg2 \
	pgadmin4 pgadmin4-desktop \

################################################################################
echo "*** Installing Google Chrome..."
dnf install -y fedora-workstation-repositories
dnf config-manager --set-enabled google-chrome
dnf install -y google-chrome-stable

################################################################################
echo "*** Installing rpmfusion..."
dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
dnf install -y https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

################################################################################
echo "*** Cleanup..."
dnf copr remove copr.fedorainfracloud.org/phracek/PyCharm

################################################################################
echo "*** Config java version..."
alternatives --config java
alternatives --config jre_openjdk

# This modules are needed by java
dnf install gtk-murrine-engine
echo "/usr/lib64/gtk-3.0/modules/" > /etc/ld.so.conf.d/pk-gtk.conf
ldconfig

