#!/bin/bash
# Script to pre-configure & install needed packages
set -e

# Run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root."
    exit
fi

################################################################################
echo "*** Installing system utilities"
dnf install -y \
	mc vim vim-X11 vim-default-editor ctags kitty xterm colordiff meld \
	smartmontools htop dnfdragora gnome-tweak-tool dconf-editor \
	curl cabextract \
	xterm xorg-x11-fonts* xorg-x11-font-utils fontconfig \
	gnome-shell-extension-common.noarch \
	gnome-shell-extension-apps-menu gnome-shell-extension-background-logo \
	gnome-shell-extension-dash-to-dock gnome-shell-extension-drive-menu \
	gnome-shell-extension-horizontal-workspaces gnome-shell-extension-launch-new-instance \
	gnome-shell-extension-places-menu gnome-shell-extension-pomodoro \
	gnome-shell-extension-system-monitor-applet gnome-shell-extension-topicons-plus \
	gnome-shell-extension-user-theme gnome-shell-extension-window-list \
	gnome-shell-extension-windowoverlay-icons gnome-shell-extension-workspace-indicator

################################################################################
echo "*** Installing development libraries"
dnf install -y \
	git git-extras git-filter-repo \
	gcc gcc-c++ make binutils automake pkg-config \
	protobuf-compiler \
	gobject-introspection-devel cairo-devel gtk3 cairo-gobject-devel \

################################################################################
echo "*** Installing tools..."
dnf install -y \
	python3 python3-pip python3-devel python3-wheel python3-setuptools python3-six \
	python3-spyder python3-notebook python-notebook-doc \
	python3-ipdb python3-coverage python3-coverage_pth python3-mock \
	python3-pytz python3-tzlocal \
	python3-numpy python3-pandas python3-scipy python3-scikit-learn python3-statsmodels \
	python3-matplotlib python3-seaborn \
	python3-defusedxml \
	python3-aiohttp \
	python3-retrying \

################################################################################
echo "*** Installing ZeroMQ..."
dnf install -y zeromq czmq python3-zmq

################################################################################
echo "*** Installing PostrgreSQL..."
dnf install -y postgresql postgresql-server postgresql-contrib postgresql-upgrade \
	postgresql-jdbc postgresql-plpython3 python3-psycopg2 \
	pgadmin4 pgadmin4-desktop

################################################################################
echo "*** Installing Google Chrome..."
FILE=/etc/yum.repos.d/google-chrome.repo
if [ -f "$FILE" ]; then
	cat <<- EOF > $FILE
	[google-chrome]
	name=google-chrome - \$basearch
	baseurl=http://dl.google.com/linux/chrome/rpm/stable/\$basearch
	enabled=1
	gpgcheck=1
	gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
	EOF
fi

dnf install -y google-chrome-stable

