#!/bin/sh

dnf upgrade --refresh
dnf install -y rpmconf dnf-plugins-core symlinks remove-retired-packages dracut-config-rescue clean-rpm-gpg-pubkey
echo "*****"
echo "* RPM verify..."
echo "*****"
rpm -Va --nofiles --nodigest

echo "*****"
echo "* DNF verify..."
echo "*****"
dnf check

echo "*****"
echo "* RPM config migration..."
echo "*****"
rpmconf -a

echo "*****"
echo "* Packages with problems..."
echo "*****"
dnf repoquery --unsatisfied

echo "*****"
echo "* Packages with orphans (list only; removed in next steps)"
echo "*****"
dnf list extras --exclude=kernel,kernel-\*,pgadmin4-\*

echo "*****"
echo "* Packages with dupes..."
echo "*****"
dnf repoquery --duplicates

echo "*****"
echo "* Packages for autoremove... (list only; removed in next steps; IMPORTANT NOT ALL SHOULD BE REMOVED)"
echo "*****"
dnf repoquery --unneeded

echo "*****"
echo "* Dangling symlinks (list only; removed in next steps)"
echo "*****"
/usr/sbin/ldconfig > /dev/null
symlinks -r /usr | grep dangling

read -rsn1 -p "Press any key to continue (orphans)"; echo

echo "*****"
echo "* Packages with orphans (cleanup)"
echo "*****"
dnf remove $(dnf repoquery --extras --exclude=kernel,kernel-\*,pgadmin4-\*)

#read -rsn1 -p "Press any key to continue (autoremove)"; echo

#echo "*****"
#echo "* Packages marked for autoremove (cleanup)"
#echo "*****"
#dnf autoremove

#read -rsn1 -p "Press any key to continue (symlinks)"; echo

#echo "*****"
#echo "* Dangling symlinks (cleanup)"
#echo "*****"
#symlinks -r -d /usr

#read -rsn1 -p "Press any key to continue (GPG keys)"; echo

#echo "*****"
#echo "* Clean-up old keys trusted for RPM package signing"
#echo "*****"
#clean-rpm-gpg-pubkey

echo "*****"
echo "* Retired packages (cleanup)"
echo "*****"
remove-retired-packages

read -rsn1 -p "Press any key to continue (full verify)"; echo

echo "*****"
echo "* Full verify..."
echo "*****"
rpm -Va >/tmp/rpm-Va.txt 2>&1
rpm -qf $(cat /tmp/rpm-Va.txt | sed 's|.* /|/|') 2>&1 | sort | uniq >/tmp/rpm-Va.pkgs.txt
egrep '^.{9}  c /' /tmp/rpm-Va.txt > /tmp/REVIEW-CONFIGS.txt
rpm -qf $(cat /tmp/REVIEW-CONFIGS.txt | sed 's|.* /|/|') 2>&1 | sort | uniq >/tmp/REVIEW-CONFIGS.pkgs.txt
egrep -v '^.{9}  c /' /tmp/rpm-Va.txt > /tmp/URGENT-REVIEW.txt
rpm -qf $(cat /tmp/URGENT-REVIEW.txt | sed 's|.* /|/|') 2>&1 | sort | uniq >/tmp/URGENT-REVIEW.pkgs.txt
find /etc /var -name '*.rpm?*' > /tmp/REVIEW-OBSOLETE-CONFIGS.txt
echo "*** /tmp/rpm-Va.txt /tmp/rpm-Va.pkgs.txt"
echo "*** /tmp/REVIEW-CONFIGS.txt /tmp/REVIEW-CONFIGS.pkgs.txt"
echo "*** /tmp/URGENT-REVIEW.txt /tmp/URGENT-REVIEW.pkgs.txt"
echo "*** /tmp/REVIEW-OBSOLETE-CONFIGS.txt"
echo "*** Permissions M,U,G -> fix using $ sudo rpm --setugids -a && sudo rpm --setperms -a"

