#!/bin/bash
set -e
TEMPLATE_DIR="$(git config --global init.templatedir)"
TEMPLATE_DIR="${TEMPLATE_DIR/#~/$HOME}"
DEST_DIR="$(git rev-parse --absolute-git-dir)"
for i in hooks info; do
	rsync -qau "$TEMPLATE_DIR/$i/" "$DEST_DIR/$i/"
done
